FROM memsql/kafka_aio

ENV AUTO_CREATE false

# 2122 is SSH, 2181 is zookeeper, 9092-9099 is kafka (for different listeners like SSL, INTERNAL, PLAINTEXT etc.)
# 8081 is the schema registry
EXPOSE 2122 2181 9092 9093 9094 9095 9096 9097 9098 9099 8081

CMD ["/scripts/start.sh"]

